# Generated by Django 3.1.4 on 2021-04-15 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210415_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employer_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_employee_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student_approvee',
            field=models.BooleanField(default=False),
        ),
    ]
