# Generated by Django 3.1.4 on 2021-04-15 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210415_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employer_student',
        ),
        migrations.AddField(
            model_name='customuser',
            name='employer_student',
            field=models.ManyToManyField(blank=True, related_name='_customuser_employer_student_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
