# Generated by Django 3.1.4 on 2021-04-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210415_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accept_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
