# Generated by Django 3.1.4 on 2021-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_accept_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accept_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
