# Generated by Django 3.1.4 on 2021-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210415_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
