# Generated by Django 3.1.4 on 2021-04-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210417_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='previous_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
