# Generated by Django 3.1.4 on 2021-04-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_previous_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_switch',
            field=models.BooleanField(default=False),
        ),
    ]
