# Generated by Django 3.1.4 on 2021-05-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_is_confirm_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='finish_approval',
            field=models.BooleanField(default=False),
        ),
    ]
