# Generated by Django 3.1.6 on 2021-04-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.TimeField(null=True)),
                ('task', models.CharField(max_length=100)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.task_type')),
            ],
        ),
    ]
