# Generated by Django 3.1.6 on 2021-04-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_list_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='list',
            name='end_datetime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='start_datetime',
            field=models.TimeField(null=True),
        ),
    ]
