# Generated by Django 3.1.6 on 2021-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210412_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='list',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='list',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
