# Generated by Django 3.1.4 on 2021-04-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tasklist_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
