# Generated by Django 3.1.4 on 2021-04-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210421_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='school_name',
            field=models.CharField(default='New Era', max_length=150),
        ),
    ]
