# Generated by Django 3.1.4 on 2021-05-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_section_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='finish_report',
            field=models.BooleanField(default=False),
        ),
    ]
